install:
  # - sudo add-apt-repository -y ppa:texlive-backports/ppa 
  # - sudo apt-get update && sudo apt-get install abntex2
  # - sudo apt-get install ttf-sil-gentium ttf-sil-gentium-basic
  # - sudo apt-get install texlive-fonts-extra ttf-inconsolata ttf-droid
  # - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
  # - sudo apt-get install texlive-latex-recommended texlive-latex-extra
  - sudo pip install pyxdameraulevenshtein
  - sudo apt-get install python-levenshtein
  - sudo pip install swalign
script:
  - make teste

notifications:
  - email: false
